version: '3.1'

services:
  postgresdb:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: db_pass
      POSTGRES_USER: db_user
      POSTGRES_DB: db_book
    ports:
      - "5432:5432"
